# Generated by Django 4.2.5 on 2023-09-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', to='ourcodeapi.coder'),
        ),
    ]
