# Generated by Django 4.2.5 on 2023-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcodeapi', '0002_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coder_images/'),
        ),
    ]
