# Generated by Django 4.2.5 on 2023-09-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourcodeapi', '0003_coder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='image',
        ),
    ]
