# Generated by Django 4.2.6 on 2023-10-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcodeapi', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(related_name='coder_liked', to='ourcodeapi.coder'),
        ),
    ]
