# Generated by Django 4.2.6 on 2023-10-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcodeapi', '0007_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likers',
            field=models.ManyToManyField(related_name='event_coder_liked', to='ourcodeapi.coder'),
        ),
    ]
